name: Supervision Release Documentation Workflow ğŸ“š
on:
  push:
    tags:
      - '[0-9]+.[0-9]+[0-9]+.[0-9]'
    branches-ignore:
      - 'develop'
  

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  pull-requests: write


jobs:
  doc-build-deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # echo github.ref
      - name: ğŸ“ Echo github.ref
        run: echo ${{ github.ref }}
      
      #Â echo github.head_ref
      - name: ğŸ“ Echo github.head_ref
        run: echo ${{ github.head_ref }}

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: ğŸ“¦ Install mkdocs-material
        run: pip install "mkdocs-material"
      - name: ğŸ“¦ Install mkdocstrings[python]
        run: pip install "mkdocstrings[python]"
      - name: ğŸ“¦ Install mkdocs-material[imaging]
        run: pip install "mkdocs-material[imaging]"
      - name: ğŸ“¦ Install mike
        run: pip install "mike"
      - name: ğŸ“¦ Install mkdocs-git-revision-date-localized-plugin
        run: pip install "mkdocs-git-revision-date-localized-plugin"
      - name: ğŸ“¦ Install JupyterLab
        run: pip install jupyterlab
      - name: ğŸ“¦ Install mkdocs-jupyter
        run: pip install mkdocs-jupyter
      - name: ğŸ“¦ Install mkdocs-git-committers-plugin-2
        run: pip install mkdocs-git-committers-plugin-2
      - name: âš™ï¸ Configure git for github-actions ğŸ‘·
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: ğŸš€ Deploy MkDoc-Material ğŸ“š
        run: |
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            MKDOCS_GIT_COMMITTERS_APIKEY=${{ secrets.GITHUB_TOKEN }} mike deploy --push --update-aliases $latest_tag latest
